### ISSUE TITLE
Error on RecyclerView

### ISSUE THREAD

**Issue by nlover6** [SecUSo/privacy-friendly-pedometer#23]
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
Process: org.secuso.privacyfriendlyactivitytracker, PID: 2287
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2457)
at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:4803)
at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:10783)
at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:10774)
at android.support.v7.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:6363)
at org.secuso.privacyfriendlyactivitytracker.fragments.WeeklyReportFragment$2.run(WeeklyReportFragment.java:341)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Comment by Yonjuni** [comment]
Thanks for the Stack Trace, could you also provide which Android version and phone model you are using?

**Comment by nlover6** [comment]
My Phone Is Sony SP And Android Version 7.1 Cyanogenmod

**Comment by licaon-kter** [comment]
So you are running Android 2.3.4 aka SDK 10?
The app needs [at least SDK 16](https://github.com/SecUSo/privacy-friendly-pedometer/blob/master/app/build.gradle#L8) aka Android 4.1.

**Comment by nlover6** [comment]
This error is a big bug!!
I test it in a tablet (Asus K012 Android 5.0 - Sony C4 Android 6.0 - Sony SP Android 7.1 ) And The error is happen.
When error happen, app force close and step counter is decrease then real count.
Ex: Real step count is 215. then app force close. then step count show 180 or less then!

**Comment by nlover6** [comment]
My Sony Sp Android is 7.1 And API (SDK) IS 25 !

**Comment by licaon-kter** [comment]
Sony SP is this http://www.gsmarena.com/sony_xperia_sp-5364.php
Cyanogenmod 7.1 is based on Android 2.3.4

What device do you have?

**Comment by Yonjuni** [comment]
Unfortunately, I cannot reproduce the error on our test devices. I see that there is some problem regarding the recycler-view. Is there any specific scenario or combination of actions that triggers this error? Or does it happen at startup?
We will of course further investigate this error, but a little more details are required that we can do this.

**Comment by nlover6** [comment]
My Sp Phone Android Version Is 7.1 Api 25 And Cyanogenmod 14.1

But i test this error in 2 other phone and tablet and this error happen.

**Comment by nlover6** [comment]
When i walk and app is open, i check my steps between day, week and month tabs , and change between these more then 2,3,... this error happen.

**Comment by Yonjuni** [comment]
@Kamuno Can you reproduce the issue?

**Comment by Yonjuni** [comment]
Okay I have reproduced it and I only occurs on Android 7 devices. It is caused by the RecyclerView adapter.  The method `notifyDataChanged()` is called from `onBindViewHolder(ViewHolder holder, int position)` and causes the problem. Thus, the call of  `notifyDataChanged()` has to be moved to the outside of  `onBindViewHolder(ViewHolder holder, int position)`

**Comment by Yonjuni** [comment]
Integrated in next update.
