### ISSUE TITLE
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-pedometer#43]
`android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6603)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:919)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1265)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.view.View.requestLayout(View.java:18738)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
	at android.view.View.requestLayout(View.java:18738)
	at android.support.v7.widget.RecyclerView.requestLayout(RecyclerView.java:3806)
	at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:4891)
	at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11101)
	at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6590)
	at org.secuso.privacyfriendlyactivitytracker.fragments.MonthlyReportFragment$2.run(MonthlyReportFragment.java:332)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)`

**Comment by Yonjuni** [comment]
Belongs #23

**Comment by Yonjuni** [comment]
Integrated in next update.
