### ISSUE TITLE
java.lang.NumberFormatException in java.lang.Integer.parseInt

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-pedometer#45]
Reported from Android 7

`java.lang.RuntimeException: Unable to create service org.secuso.privacyfriendlyactivitytracker.services.HardwareStepDetectorService: java.lang.NumberFormatException: For input string: ""
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3201)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:533)
	at java.lang.Integer.parseInt(Integer.java:556)
	at org.secuso.privacyfriendlyactivitytracker.services.AbstractStepDetectorService.onCreate(AbstractStepDetectorService.java:191)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3191)
	... 8 more
`

**Comment by Yonjuni** [comment]
Integrated in next update.
