### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by matthiasbeyer** [SecUSo/privacy-friendly-pedometer#82]
Export fails. That's all I can tell you, as there is no more information displayed, unfortunately.

**Comment by sleep-yearning** [comment]
Can you check if you gave Storage permission to the app?
This could be an issue. You can check it in the Android App Information view under Permissions.

**Comment by matthiasbeyer** [comment]
The app has access to the file storage.

**Comment by Ythogtha** [comment]
I have the same problem here, since around last May at least.
A message appears briefly stating that « an error occurred during export ».
And, well, I have no exported file anywhere.
I've checked permissions multiple times, removed and re-added them, waited for updates, nothing seems to help.
I would like not to try removing then reinstalling, it may solve the problem (who knows ?), but I'd have lost all previous datas...

**Comment by otrichet** [comment]
On Android 12, the relevant logcat output when export fails (using f-droid built 3.0.0):

```
11-09 18:53:52.070  4910 30980 E MediaProvider: insertFileIfNecessary failed
11-09 18:53:52.070  4910 30980 E MediaProvider: java.lang.IllegalArgumentException: Primary directory null not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:4021)
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:3659)
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:4431)
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:5017)
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.insert(MediaProvider.java:4717)
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:9305)
11-09 18:53:52.070  4910 30980 E MediaProvider:         at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:9400)
11-09 18:53:52.077  1965  3666 D OplusNotificationManagerServiceExtImpl: shouldInterceptToast: 
11-09 18:53:52.083 14244 14244 W System.err: java.io.IOException: Operation not permitted
11-09 18:53:52.087 14244 14244 W System.err:    at java.io.UnixFileSystem.createFileExclusively0(Native Method)
11-09 18:53:52.087 14244 14244 W System.err:    at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
11-09 18:53:52.087 14244 14244 W System.err:    at java.io.File.createNewFile(File.java:1006)
11-09 18:53:52.087 14244 14244 W System.err:    at org.secuso.privacyfriendlyactivitytracker.activities.PreferencesActivity$GeneralPreferenceFragment.generateCSVToExport(PreferencesActivity.java:452)
11-09 18:53:52.087 14244 14244 W System.err:    at org.secuso.privacyfriendlyactivitytracker.activities.PreferencesActivity$GeneralPreferenceFragment$3.onPreferenceClick(PreferencesActivity.java:355)
11-09 18:53:52.087 14244 14244 W System.err:    at android.preference.Preference.performClick(Preference.java:1165)
11-09 18:53:52.087 14244 14244 W System.err:    at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:261)
11-09 18:53:52.087 14244 14244 W System.err:    at android.widget.AdapterView.performItemClick(AdapterView.java:352)
11-09 18:53:52.087 14244 14244 W System.err:    at android.widget.AbsListView.performItemClick(AbsListView.java:1235)
11-09 18:53:52.087 14244 14244 W System.err:    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3232)
11-09 18:53:52.087 14244 14244 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
11-09 18:53:52.087 14244 14244 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-09 18:53:52.087 14244 14244 W System.err:    at android.os.Looper.loopOnce(Looper.java:233)
11-09 18:53:52.087 14244 14244 W System.err:    at android.os.Looper.loop(Looper.java:344)
11-09 18:53:52.087 14244 14244 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:8210)
11-09 18:53:52.087 14244 14244 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-09 18:53:52.087 14244 14244 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
11-09 18:53:52.087 14244 14244 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
11-09 18:53:52.088 14244 14244 I Quality : Skipped: false 2 cost 47.438118 refreshRate 16666666 processName org.secuso.privacyfriendlyactivitytracker
```

This might be related to the enhanced restriction to the file system write access introduced in Android 11 (https://developer.android.com/about/versions/11/privacy/storage).

**Comment by Ythogtha** [comment]
I should have said, I'm using LineageOS 19, which is Android 12.
And yes, it seems file system access are more fine-grained, allowing specific directories.
Apparently Download and Documents directories are accessible, and for other ones they may need to be asked specifically.
Maybe the easier fix would be to save in Download directory, or to try to fall back on it if standard location doesn't work.

**Comment by Ythogtha** [comment]
Ok, that might help :
In android settings for developers, looking for compatibility parameters for application (somewhere after GPU debugging options on my device), searching for pedometer, and unchecking DEFAULT_SCOPED_STORAGE allows exporting the datas.

**Comment by Ythogtha** [comment]
But today, all dates on the exported CSV file are "1970-01-01 01:00:00".
Though I don't think this issue is related to the one we are talking about.
