### ISSUE TITLE
"Correct steps" option causes app crash

### ISSUE THREAD

**Issue by Terrance** [SecUSo/privacy-friendly-pedometer#86]
Updated to v2.4 today, and the option to correct your step count seems to immediately crash the app when selected:

```
07-22 13:51:49.501  2617  2617 E AndroidRuntime: FATAL EXCEPTION: main
07-22 13:51:49.501  2617  2617 E AndroidRuntime: Process: org.secuso.privacyfriendlyactivitytracker, PID: 2617
07-22 13:51:49.501  2617  2617 E AndroidRuntime: android.view.InflateException: Binary XML file line #25 in org.secuso.privacyfriendlyactivitytracker:layout/dialog_correct_steps: Binary XML file line #25 in org.secuso.privacyfriendlyactivitytracker:layout/dialog_correct_steps: Error inflating class android.support.design.widget.TextInputLayout
07-22 13:51:49.501  2617  2617 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #25 in org.secuso.privacyfriendlyactivitytracker:layout/dialog_correct_steps: Error inflating class android.support.design.widget.TextInputLayout
07-22 13:51:49.501  2617  2617 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.support.design.widget.TextInputLayout
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at java.lang.Class.forName(Class.java:454)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at org.secuso.privacyfriendlyactivitytracker.fragments.DailyReportFragment.onWalkingModeClicked(DailyReportFragment.java:587)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at org.secuso.privacyfriendlyactivitytracker.adapters.ReportAdapter$SummaryViewHolder.onMenuItemClick(ReportAdapter.java:490)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:4116)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
07-22 13:51:49.501  2617  2617 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.support.design.widget.TextInputLayout
07-22 13:51:49.501  2617  2617 E AndroidRuntime:        ... 28 more
```

**Comment by msq-ie** [comment]
That was also my experience with all 2.x versions I tried.

**Comment by Terrance** [comment]
This was apparently fixed a month ago, but hasn't yet made it into a release.  Will a new version be made available in the Play Store any time soon?
